// Generated by https://quicktype.io

export interface ClimateData {
    pagination: Pagination;
    results: { [key: string]: string }[];
}

export interface Pagination {
    pageSize: number;
    page: number;
    total: number;
}


